name: My Project CI
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code form Github
        uses: actions/checkout@v3
      - name: Setup node js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code form Github
        uses: actions/checkout@v3
      - name: Setup node js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
  build:
    needs: [test, lint]
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code form Github
        uses: actions/checkout@v3
      - name: Setup node js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependenciess
        run: npm ci
      - name: Run tests
        run: npm run test 